#
# Copyright (c) 2017 Oracle and/or its affiliates. All rights reserved.
#

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rest-jscreditscore
  labels:
    run: rest-jscreditscore
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: rest-jscreditscore
    spec:
      containers:
      - image: iad.ocir.io/gse00014520/angular-node-creditscore:master-309e31914ded5451cd87b3999abb86bf57d9d285
        imagePullPolicy: Always
        name: rest-jscreditscore
        ports:
        - containerPort: 3000
          protocol: TCP
      imagePullSecrets:
      - name: mysecretk8s
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rest-jscreditscore-svc
spec:
  selector:
    run: rest-jscreditscore
  ports:
    - port: 8088
      targetPort: 3000
  type: ClusterIP
